# fly.toml app configuration file generated for yoga-website on 2025-08-29T16:55:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yoga-website'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[mounts]
  source="yoga_data"
  destination="/data"

[env]
  DATABASE_PATH="/data/yoga.db"
